name: fieldforce
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  flutter_screenutil: ^0.6.0
  splashscreen: ^1.2.0
  country_pickers: ^1.1.0
  flutter_svg: ^0.19.0
  country_code_picker: ^1.2.2
  fluttertoast: ^3.1.3
  progress_dialog: ^1.2.0
  shared_preferences: ^0.5.3+4
  pin_code_text_field: ^1.5.1
  percent_indicator: ^2.1.1+1
  grouped_buttons: ^1.0.4
  timeline_list: ^0.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  fonts:
    - family: Gilroy-Light
      fonts:
        - asset: fonts/Gilroy-Light.otf

    - family: Gilroy-ExtraBold
      fonts:
        - asset: fonts/Gilroy-ExtraBold.otf

    - family: Inter-Black
      fonts:
        - asset: fonts/Inter-Black.ttf

    - family: Inter-Bold
      fonts:
        - asset: fonts/Inter-Bold.ttf

    - family: Inter-ExtraBold
      fonts:
        - asset: fonts/Inter-ExtraBold.ttf

    - family: Inter-ExtraLight
      fonts:
        - asset: fonts/Inter-ExtraLight-BETA.ttf

    - family: Inter-Light
      fonts:
        - asset: fonts/Inter-Light-BETA.ttf

    - family: Inter-Medium
      fonts:
        - asset: fonts/Inter-Medium.ttf

    - family: Inter-Regular
      fonts:
        - asset: fonts/Inter-Regular.ttf

    - family: Inter-SemiBold
      fonts:
        - asset: fonts/Inter-SemiBold.ttf

    - family: Inter-Thin-BETA
      fonts:
        - asset: fonts/Inter-Thin-BETA.ttf
    
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-ExtraBold.otf 
    
    - family: RedHat
      fonts:
        - asset: fonts/RedHatText-Bold.otf
    
    - family: Poppins-Thin
      fonts:
        - asset: fonts/Poppins-Thin.otf 
assets:
  - images/trips/chevron-down.svg
  - images/trips/filter.svg
  - images/trips/search.svg
  - images/trips/alert.svg
  - images/Tig-rips/done.svg
  - images/Homepage/triplist.svg
  - images/Homepage/triphistory.svg
  - images/Homepage/more-vertical.svg
  - images/Homepage/alertbell.svg
  - images/Homepage/settings.svg
  - images/Homepage/matching.svg
  - images/Homepage/bluetooth.svg
  - images/Homepage/temperature.svg
  - images/TripLegs/back.svg
  - images/TripLegs/camera.svg
  - images/TripLegs/callsupport.svg
  - images/TripLegs/edit.svg
  - images/TripLegs/map.svg
  - images/TripLegs/menu.svg
  - images/TripLegs/radio.svg
  - images/TripLegs/right.svg
  - images/TripLegs/close.svg
  - images/TripLegs/error.svg
  - images/Logo/logo.png